using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace uOrgHub.Shared.Entities;

/// <summary>
/// A file attached to any business record in the system. The pairing of <see cref="EntityType"/>
/// and <see cref="EntityId"/> points at the owning record — "Voucher" + a voucher id, for example —
/// so every module shares this one table and one set of endpoints instead of building its own.
/// The bytes live on disk under the configured storage root; this row holds only metadata.
/// </summary>
[Table("attachments")]
public class Attachment : BaseEntity
{
    /// <summary>Short name of the owning record type, e.g. "Voucher". Registered targets only.</summary>
    [Required]
    [MaxLength(100)]
    public string EntityType { get; set; } = string.Empty;

    /// <summary>Id of the record this file belongs to.</summary>
    public Guid EntityId { get; set; }

    /// <summary>The file's original name as chosen by the user, kept for display and download.</summary>
    [Required]
    [MaxLength(255)]
    public string FileName { get; set; } = string.Empty;

    /// <summary>
    /// Relative path of the stored file inside the storage root. Generated by the storage service,
    /// never user-supplied, so it is safe to resolve on disk without path-traversal risk.
    /// </summary>
    [Required]
    [MaxLength(300)]
    public string StorageKey { get; set; } = string.Empty;

    /// <summary>MIME type recorded at upload time, e.g. "image/png" or "application/pdf".</summary>
    [Required]
    [MaxLength(100)]
    public string ContentType { get; set; } = string.Empty;

    /// <summary>File size in bytes.</summary>
    public long FileSizeBytes { get; set; }

    /// <summary>Optional free-text note about what the file shows or why it was attached.</summary>
    [MaxLength(500)]
    public string? Description { get; set; }
}
