// Shared print facility — mirrors the accounting module's ReportLayout print popup.
// Opens a new window with a consistent header/footer and triggers the browser print dialog.

interface PrintOptions {
  title: string;
  subtitle?: string;
  /** Pre-rendered HTML for the document body (e.g. a <table>). */
  bodyHtml: string;
}

function escapeHtml(value: unknown): string {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

export function openPrintWindow({ title, subtitle, bodyHtml }: PrintOptions) {
  const printWindow = window.open("", "_blank");
  if (!printWindow) return;
  const now = new Date().toLocaleString("en-BD");
  printWindow.document.write(`
    <html>
      <head>
        <title>${escapeHtml(title)}</title>
        <script src="https://cdn.tailwindcss.com"></script>
        <style>
          @page { margin: 15mm; }
          body { font-family: 'Inter', sans-serif; color: #1f2937; -webkit-print-color-adjust: exact; }
          .print-header { text-align: center; margin-bottom: 1.5rem; }
          table { width: 100%; border-collapse: collapse; font-size: 12px; }
          th, td { text-align: left; padding: 6px 8px; border-bottom: 1px solid #e5e7eb; }
          thead th { background: #f9fafb; font-weight: 600; color: #374151; border-bottom: 1px solid #d1d5db; }
          .print-footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 10px; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 4px; }
          @media print { .no-print { display: none !important; } }
        </style>
      </head>
      <body>
        <div class="print-header">
          <h1 style="font-size:18px; font-weight:600; margin:0;">${escapeHtml(title)}</h1>
          ${subtitle ? `<p style="font-size:12px; color:#6b7280; margin:4px 0 0;">${escapeHtml(subtitle)}</p>` : ""}
          <p style="font-size:10px; color:#9ca3af; margin:4px 0;">Printed: ${escapeHtml(now)}</p>
        </div>
        ${bodyHtml}
        <div class="print-footer">Generated by uOrgHub</div>
        <script>window.print();</script>
      </body>
    </html>
  `);
  printWindow.document.close();
}

export interface PrintColumn<T> {
  header: string;
  value: (row: T) => string | number;
}

/** Build a simple HTML table from columns + rows for use with openPrintWindow. */
export function buildPrintTable<T>(columns: PrintColumn<T>[], rows: T[]): string {
  const head = columns.map((c) => `<th>${escapeHtml(c.header)}</th>`).join("");
  const body = rows.length
    ? rows
        .map(
          (row) =>
            `<tr>${columns.map((c) => `<td>${escapeHtml(c.value(row))}</td>`).join("")}</tr>`,
        )
        .join("")
    : `<tr><td colspan="${columns.length}" style="text-align:center; color:#9ca3af; padding:24px;">No records found</td></tr>`;
  return `<table><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table>`;
}
