#!/usr/bin/env bash
# =============================================================================
#  uOrgHub — First-Time Production Deployment Script
#  Server : 62.84.181.246 (Ubuntu)
#  Domain : uorghub.unitymicrofund.com
#
#  Usage  : bash deploy.sh
#  Run as : root
# =============================================================================
set -euo pipefail

# ── Configuration ─────────────────────────────────────────────────────────────
DOMAIN="uorghub.unitymicrofund.com"
REPO_URL="https://github.com/golamhabibpalash/uOrgHub.git"
DEPLOY_DIR="/opt/uorghub"
SSL_EMAIL="admin@unitymicrofund.com"          # Used for Let's Encrypt notifications
COMPOSE_FILE="$DEPLOY_DIR/docker-compose.prod.yml"
ENV_FILE="$DEPLOY_DIR/.env"
NGINX_AVAILABLE="/etc/nginx/sites-available/uorghub"
NGINX_ENABLED="/etc/nginx/sites-enabled/uorghub"

# ── Colours ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
log()  { echo -e "${GREEN}[✔]${NC} $*"; }
info() { echo -e "${CYAN}[→]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*"; }
die()  { echo -e "${RED}[✘] ERROR:${NC} $*" >&2; exit 1; }

# ── Guards ────────────────────────────────────────────────────────────────────
[[ $EUID -eq 0 ]] || die "Run this script as root: sudo bash deploy.sh"
[[ $(uname -s) == "Linux" ]] || die "This script targets Linux (Ubuntu)."

echo ""
echo -e "${CYAN}╔══════════════════════════════════════════════╗"
echo -e "║     uOrgHub Production Deployment           ║"
echo -e "╚══════════════════════════════════════════════╝${NC}"
echo ""

# ── 1. Install system dependencies ───────────────────────────────────────────
info "Checking system dependencies..."
apt-get update -qq

if ! command -v docker &>/dev/null; then
    info "Installing Docker..."
    curl -fsSL https://get.docker.com | sh
    systemctl enable docker
    systemctl start docker
    log "Docker installed."
else
    log "Docker already installed: $(docker --version)"
fi

if ! docker compose version &>/dev/null; then
    info "Installing Docker Compose plugin..."
    apt-get install -y -qq docker-compose-plugin
    log "Docker Compose plugin installed."
else
    log "Docker Compose: $(docker compose version --short)"
fi

if ! command -v nginx &>/dev/null; then
    info "Installing nginx..."
    apt-get install -y -qq nginx
    systemctl enable nginx
    systemctl start nginx
    log "nginx installed."
else
    log "nginx already installed: $(nginx -v 2>&1)"
fi

if ! command -v certbot &>/dev/null; then
    info "Installing certbot..."
    apt-get install -y -qq certbot python3-certbot-nginx
    log "certbot installed."
else
    log "certbot already installed."
fi

# ── 2. Clone or update repository ────────────────────────────────────────────
info "Setting up repository at $DEPLOY_DIR..."

if [[ -d "$DEPLOY_DIR/.git" ]]; then
    log "Repository already cloned. Pulling latest..."
    git -C "$DEPLOY_DIR" pull
else
    info "Cloning $REPO_URL → $DEPLOY_DIR"
    git clone "$REPO_URL" "$DEPLOY_DIR"
    log "Repository cloned."
fi

# ── 3. Create .env file ───────────────────────────────────────────────────────
if [[ -f "$ENV_FILE" ]]; then
    warn ".env already exists at $ENV_FILE — skipping creation."
    warn "To recreate it, delete the file and re-run this script."
else
    info "Creating .env file (secrets will not be echoed)..."
    echo ""

    while true; do
        read -rsp "  Database password: " DB_PASSWORD; echo
        read -rsp "  Confirm password : " DB_CONFIRM; echo
        [[ "$DB_PASSWORD" == "$DB_CONFIRM" ]] && break
        warn "Passwords do not match. Try again."
    done

    while true; do
        read -rsp "  JWT secret key (min 32 chars): " JWT_SECRET; echo
        [[ ${#JWT_SECRET} -ge 32 ]] && break
        warn "JWT secret must be at least 32 characters."
    done

    cat > "$ENV_FILE" <<EOF
# Generated by deploy.sh — keep this file secret
DB_USER=postgres
DB_PASSWORD=${DB_PASSWORD}
DB_NAME=orgHub
JWT_SECRET=${JWT_SECRET}
VITE_API_URL=https://${DOMAIN}/api/v1
ALLOWED_ORIGINS=https://${DOMAIN}
EOF
    chmod 600 "$ENV_FILE"
    log ".env created at $ENV_FILE"
fi

# ── 4. Build and start Docker containers ─────────────────────────────────────
info "Building Docker images and starting containers..."
cd "$DEPLOY_DIR"
docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" up -d --build

log "Containers started."

# ── 5. Wait for API to respond ────────────────────────────────────────────────
info "Waiting for API to be ready (up to 60 s)..."
for i in $(seq 1 30); do
    if curl -sf --max-time 2 http://127.0.0.1:5177/api/v1/health &>/dev/null 2>&1 || \
       docker inspect --format='{{.State.Status}}' uorghub-api 2>/dev/null | grep -q "running"; then
        break
    fi
    sleep 2
done
log "API container is running."

# ── 6. Configure nginx ────────────────────────────────────────────────────────
info "Configuring nginx..."

# First, write an HTTP-only config so certbot can do the ACME challenge
mkdir -p /var/www/html

cat > "$NGINX_AVAILABLE" <<NGINX_HTTP
server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN};

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 200 'uOrgHub — pending SSL setup';
        add_header Content-Type text/plain;
    }
}
NGINX_HTTP

# Enable the site
ln -sf "$NGINX_AVAILABLE" "$NGINX_ENABLED"

# Remove the default nginx site if it exists to avoid conflicts
rm -f /etc/nginx/sites-enabled/default

nginx -t && nginx -s reload
log "nginx serving HTTP on port 80."

# ── 7. Obtain SSL certificate ─────────────────────────────────────────────────
info "Checking DNS resolution for $DOMAIN..."
RESOLVED_IP=$(dig +short "$DOMAIN" 2>/dev/null | tail -n1 || true)
if [[ -z "$RESOLVED_IP" ]]; then
    warn "Could not resolve $DOMAIN. Make sure the DNS A record points to this server."
    warn "Skipping SSL certificate for now. Run scripts/ssl-renew.sh after DNS is configured."
else
    info "Domain resolves to: $RESOLVED_IP"

    if [[ -f "/etc/letsencrypt/live/${DOMAIN}/fullchain.pem" ]]; then
        log "SSL certificate already exists. Skipping."
    else
        info "Obtaining SSL certificate via Let's Encrypt..."
        certbot certonly \
            --webroot \
            --webroot-path /var/www/html \
            -d "$DOMAIN" \
            --email "$SSL_EMAIL" \
            --agree-tos \
            --non-interactive \
            --quiet

        log "SSL certificate obtained."
    fi

    # Write the full HTTPS nginx config from the repo
    cp "$DEPLOY_DIR/nginx/uorghub.conf" "$NGINX_AVAILABLE"
    ln -sf "$NGINX_AVAILABLE" "$NGINX_ENABLED"
    nginx -t && nginx -s reload
    log "nginx configured with HTTPS."
fi

# ── 8. Set up automatic SSL renewal ──────────────────────────────────────────
info "Setting up automatic SSL certificate renewal..."
CRON_JOB="0 3 * * * certbot renew --quiet --post-hook 'nginx -s reload'"
if crontab -l 2>/dev/null | grep -q "certbot renew"; then
    log "Certbot renewal cron already configured."
else
    (crontab -l 2>/dev/null; echo "$CRON_JOB") | crontab -
    log "Renewal cron job added (runs daily at 03:00)."
fi

# ── 9. Final status ───────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════╗"
echo -e "║          Deployment Successful! ✔            ║"
echo -e "╠══════════════════════════════════════════════╣"
echo -e "║  App     : https://${DOMAIN}  ║"
echo -e "║  Swagger : https://${DOMAIN}/swagger  ║"
echo -e "║  Deploy  : $DEPLOY_DIR              ║"
echo -e "╠══════════════════════════════════════════════╣"
echo -e "║  Update  : bash scripts/update.sh            ║"
echo -e "╚══════════════════════════════════════════════╝${NC}"
echo ""

info "Container status:"
docker compose -f "$COMPOSE_FILE" ps
