using FluentAssertions;
using uOrgHub.Accounts.Models.Entities;
using uOrgHub.Accounts.Models.Enums;
using uOrgHub.Accounts.Services;
using uOrgHub.Shared.Data;
using uOrgHub.Shared.Exceptions;

namespace uOrgHub.Tests.Accounts;

/// <summary>
/// A journal entry generated by a document belongs to that document's workflow. Reaching it
/// directly from the Journal Entries screen would let a voucher's money hit the ledger before the
/// voucher was approved — and leave the voucher reading "Submitted" for a posted transaction.
/// </summary>
public class JournalEntrySourceServiceTests
{
    private static AppDbContext NewContext()
        => TestDb.NewContext("TestDb_JournalEntrySource_" + Guid.NewGuid());

    private static JournalEntry SeedEntry(AppDbContext ctx, string number = "JV-2026-0001")
    {
        var entry = new JournalEntry
        {
            Id = Guid.NewGuid(),
            EntryNumber = number,
            EntryDate = new DateTime(2026, 8, 12),
            Description = "Entry",
            Status = JournalEntryStatus.Draft,
        };
        ctx.Set<JournalEntry>().Add(entry);
        ctx.SaveChanges();
        return entry;
    }

    private static void SeedVoucher(AppDbContext ctx, Guid journalEntryId, VoucherStatus status, string number = "DR-2026-0001")
    {
        ctx.Set<Voucher>().Add(new Voucher
        {
            Id = Guid.NewGuid(),
            VoucherNumber = number,
            VoucherType = VoucherType.Debit,
            VoucherDate = new DateTime(2026, 8, 12),
            Description = "Site materials",
            DebitAccountId = Guid.NewGuid(),
            CreditAccountId = Guid.NewGuid(),
            Amount = 5000m,
            Status = status,
            JournalEntryId = journalEntryId,
        });
        ctx.SaveChanges();
    }

    private static JournalEntrySourceService Service(AppDbContext ctx) => new(ctx);

    // --- Resolving the source ---

    [Fact]
    public async Task A_hand_written_entry_has_no_source()
    {
        using var ctx = NewContext();
        var entry = SeedEntry(ctx);

        (await Service(ctx).FindSourceAsync(entry.Id)).Should().BeNull();
    }

    [Fact]
    public async Task An_entry_generated_by_a_voucher_reports_that_voucher()
    {
        using var ctx = NewContext();
        var entry = SeedEntry(ctx);
        SeedVoucher(ctx, entry.Id, VoucherStatus.Submitted);

        var source = await Service(ctx).FindSourceAsync(entry.Id);

        source.Should().NotBeNull();
        source!.DocumentType.Should().Be("Voucher");
        source.DocumentNumber.Should().Be("DR-2026-0001");
        source.DocumentStatus.Should().Be("Submitted");
    }

    [Fact]
    public async Task A_bill_is_recognised_as_a_source()
    {
        using var ctx = NewContext();
        var entry = SeedEntry(ctx);
        ctx.Set<Bill>().Add(new Bill
        {
            Id = Guid.NewGuid(),
            BillNumber = "BILL-0001",
            VendorId = Guid.NewGuid(),
            FiscalYearId = Guid.NewGuid(),
            BillDate = new DateTime(2026, 8, 12),
            DueDate = new DateTime(2026, 9, 12),
            Status = BillStatus.Received,
            JournalEntryId = entry.Id,
        });
        ctx.SaveChanges();

        var source = await Service(ctx).FindSourceAsync(entry.Id);

        source!.DocumentType.Should().Be("Bill");
        source.DocumentNumber.Should().Be("BILL-0001");
    }

    /// <summary>A deleted document no longer owns anything — its entry is free again.</summary>
    [Fact]
    public async Task A_deleted_voucher_no_longer_owns_its_entry()
    {
        using var ctx = NewContext();
        var entry = SeedEntry(ctx);
        SeedVoucher(ctx, entry.Id, VoucherStatus.Submitted);
        var voucher = ctx.Set<Voucher>().First();
        voucher.IsDeleted = true;
        ctx.SaveChanges();

        (await Service(ctx).FindSourceAsync(entry.Id)).Should().BeNull();
    }

    [Fact]
    public async Task Sources_for_a_page_resolve_in_one_batch()
    {
        using var ctx = NewContext();
        var owned = SeedEntry(ctx, "JV-2026-0001");
        var manual = SeedEntry(ctx, "JV-2026-0002");
        SeedVoucher(ctx, owned.Id, VoucherStatus.Approved);

        var sources = await Service(ctx).FindSourcesAsync(new[] { owned.Id, manual.Id });

        sources.Should().ContainKey(owned.Id);
        sources.Should().NotContainKey(manual.Id);
    }

    // --- The guard ---

    [Fact]
    public async Task A_hand_written_entry_may_be_acted_on_directly()
    {
        using var ctx = NewContext();
        var entry = SeedEntry(ctx);

        var act = () => Service(ctx).EnsureNotDocumentOwnedAsync(entry.Id, "posted");

        await act.Should().NotThrowAsync();
    }

    /// <summary>
    /// The heart of it: an unapproved voucher's entry must not be postable from the journal screen.
    /// </summary>
    [Fact]
    public async Task Posting_an_unapproved_vouchers_entry_directly_is_blocked()
    {
        using var ctx = NewContext();
        var entry = SeedEntry(ctx);
        SeedVoucher(ctx, entry.Id, VoucherStatus.Submitted);

        var act = () => Service(ctx).EnsureNotDocumentOwnedAsync(entry.Id, "posted");

        (await act.Should().ThrowAsync<AppException>())
            .Which.Message.Should()
                .Contain("DR-2026-0001").And
                .Contain("Submitted").And
                .Contain("Approve and post the voucher");
    }

    /// <summary>
    /// Blocked even once approved. Posting through the journal screen would move the money without
    /// advancing the voucher, so the two records would disagree about what had happened.
    /// </summary>
    [Fact]
    public async Task Posting_an_approved_vouchers_entry_directly_is_also_blocked()
    {
        using var ctx = NewContext();
        var entry = SeedEntry(ctx);
        SeedVoucher(ctx, entry.Id, VoucherStatus.Approved);

        var act = () => Service(ctx).EnsureNotDocumentOwnedAsync(entry.Id, "posted");

        await act.Should().ThrowAsync<AppException>();
    }

    [Theory]
    [InlineData("edited")]
    [InlineData("deleted")]
    [InlineData("cancelled")]
    public async Task Every_direct_mutation_of_an_owned_entry_is_blocked(string action)
    {
        using var ctx = NewContext();
        var entry = SeedEntry(ctx);
        SeedVoucher(ctx, entry.Id, VoucherStatus.Approved);

        var act = () => Service(ctx).EnsureNotDocumentOwnedAsync(entry.Id, action);

        (await act.Should().ThrowAsync<AppException>())
            .Which.Message.Should().Contain(action);
    }
}
